### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Sigmanor** [NicoSantangelo/sublime-gulp#32]
<b>Sublime Text 3 Build 3083
WIndows 8.1</b>

After chose gulp in Command Palette nothing happens, project files does not built.

![](http://i.imgur.com/Xc0Hj0N.png)

<b>Console:</b>

<pre>
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "D:\Program Files\Sublime Text\Data\Packages\Gulp\gulp.py", line 464, in run
    self.result = self.target(*self.args)
  File "D:\Program Files\Sublime Text\Data\Packages\Gulp\gulp.py", line 299, in _pipe_stream
    output_line = self.decode_line(line)
  File "D:\Program Files\Sublime Text\Data\Packages\Gulp\gulp.py", line 306, in decode_line
    return str(line.decode('utf-8') if sys.version_info >= (3, 0) else line) + "\n"
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 7: invalid start byte
</pre>

**Comment by NicoSantangelo** [comment]
I'll look into it!

If it's not a problem, can you post here the output of the `default` task when you run it from a terminal? Thanks!

**Comment by Sigmanor** [comment]
@NicoSantangelo 

<pre>
Microsoft Windows [Version 6.3.9600]
(c) Корпорация Майкрософт (Microsoft Corporation), 2013. Все права защищены.

D:\project-1\node_modules\.bin>gulp
[16:30:00] Working directory changed to D:\project-1
[16:30:02] Using gulpfile D:\project-1\gulpfile.js
[16:30:02] Starting 'html:build'...
[16:30:02] Finished 'html:build' after 7.62 ms
[16:30:02] Starting 'agl:build'...
[16:30:02] Finished 'agl:build' after 2.55 ms
[16:30:02] Starting 'js:build'...
[16:30:02] Finished 'js:build' after 2.73 ms
[16:30:02] Starting 'style:build'...
[16:30:02] Finished 'style:build' after 4.48 ms
[16:30:02] Starting 'image:build'...
[16:30:02] Finished 'image:build' after 3.19 ms
[16:30:02] Starting 'build'...
[16:30:02] Finished 'build' after 3.95 ?s
[16:30:02] Starting 'lr'...
[16:30:02] Finished 'lr' after 40 ms
[16:30:02] Starting 'watch'...
[16:30:02] Finished 'watch' after 6.1 ms
[16:30:02] Starting 'default'...
[16:30:02] Finished 'default' after 3.95 ?s
[16:30:03] D:\project-1\build\sigmanor.tk\err404.html reloaded.

[16:30:03] D:\project-1\build\sigmanor.tk\style\bootstrap.css r
eloaded.
[16:30:03] D:\project-1\build\sigmanor.tk\aion-game-launcher\hi
story.html reloaded.
[16:30:03] D:\project-1\build\sigmanor.tk\index.html reloaded.
[16:30:03] D:\project-1\build\sigmanor.tk\style\main.css reload
ed.
[16:30:03] D:\project-1\build\sigmanor.tk\aion-game-launcher\in
dex.html reloaded.
[16:30:04] D:\project-1\build\sigmanor.tk\aion-game-launcher\ma
nual.html reloaded.
[16:30:09] gulp-imagemin: Minified 39 images (saved 976.43 kB - 24.5%)

</pre>

**Comment by NicoSantangelo** [comment]
Thanks again, I'll try to get an environment where I can test the error properly and I'll let you know.

**Comment by Sigmanor** [comment]
@NicoSantangelo many thanks for the quick response!

**Comment by NicoSantangelo** [comment]
Oh! One last thing has sublime gulp work for you before or is it the first time you use it?

**Comment by Sigmanor** [comment]
@NicoSantangelo  It was the first time when I decided to try this package.

**Comment by NicoSantangelo** [comment]
@Sigmanor I can't really recreate the bug (yet), it seems to be tied to the Windows language.

That being said I've added a patch to see if the task can run anyways, could you test it if you have some time? (the patch is in the last version, 4.4.2)

**Comment by Sigmanor** [comment]
@NicoSantangelo error :disappointed: 

![](http://i.imgur.com/eOypxUb.png)

**Comment by NicoSantangelo** [comment]
Ohh :(.
I can I bother you again when you have the time?, could you try deleting your `.sublime-gulp.cache` (if any), trying again and letting me know where it blows up? (and the stack trace from the console if you can)

Because for what I can see, this last time you couldn't even pick a task? so it should be another error...I hope.

I'm not very fond of making you test this for me, but I didn't find another way just yet, sorry.

**Comment by Sigmanor** [comment]
@NicoSantangelo Now i got this strange error

![default](https://cloud.githubusercontent.com/assets/7986067/8433482/ba48510c-1f4e-11e5-80c7-6d98e1726bac.png)

And there are no errors in sublime console. Its on ctrl+` right? (sorry, I don't really know)

**Comment by NicoSantangelo** [comment]
Ok! that "makes sense" (yes! that's the console, thanks!)

The last patch I uploaded tells Python to replace replace data with a suitable replacement marker instead of blowing up. So that means that it's not being able to decode the `gulp` output to `utf-8`.

Well, this is a though one, I need to figure out why the decoding isn't working and then I have to fix it. So, one last thing, which Windows version are you using? are you using a different language pack?

Thanks a lot for all your help, I'll let you know when I have something, I'll try my best to recreate it in a local environment.

**Comment by Sigmanor** [comment]
I have Windows 8.1 Single Language

Console output:

![](http://i.imgur.com/ntmcOdj.png)

**Comment by Sigmanor** [comment]
Well, package seems working fine now :smile:

**Comment by NicoSantangelo** [comment]
Wohoo!

I was able to fix the normal output of the command, but there's still an issue with STDERR, meaning that if `gulp` fails or isn't installed the output will be gibberish.

So! I'll close this issue and open a new one with this specific problem.

Thanks for being patient!
