### ISSUE TITLE
Node/Gulp Error

### ISSUE THREAD

**Issue by onlyskyguy** [NicoSantangelo/sublime-gulp#50]
The solution to this might be somewhere in the gulp-sass arena, but I'm only getting the following error when I run gulp with sublime-gulp. If I run normally from a terminal it works fine.

```
Error: `libsass` bindings not found in [AppPath]/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath ([AppPath]/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> ([AppPath]/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([AppPath]/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([AppPath]/gulpfile.js:39:11)
```

I'm wondering if I've got something setup incorrectly in the sublime-gulp settings for this to happen.

Running Ubuntu Linux 
    gulp --version
    [00:23:30] CLI version 3.8.11
    [00:23:30] Local version 3.9.0
    
    node --version    
    v0.12.2

gulp.sublime-settings
```
"exec_args": {
	"path": "/bin:/usr/bin:/usr/local/bin:node_modules/.bin"
}
```

Thanks for any insight into this.

**Comment by NicoSantangelo** [comment]
Hmmm, your settings seem right.

I think this might be a problem with the fact that `gulp-sass` is a wrapper around `node-sass`, which is a node binding for `libsass`, which is a port of `Sass`. So it's very likely that one of those projects it's getting confused with the PATH.

Does the command work in the terminal?

**Comment by onlyskyguy** [comment]
Yes it works great in terminal.

Yeah there's a lot sass going on :p

**Comment by NicoSantangelo** [comment]
Welp, I'm having the same error and it's not an easy fix :(
I'll let you know if I find something

**Comment by onlyskyguy** [comment]
Does it have to do with local node files vs global? Or due to all the
wrapper action involved with libsass
