### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by maheshjag** [NicoSantangelo/sublime-gulp#58]
I've got a project with a Gulpfile.js (case-sensitive file name). When I try to "List Gulp Tasks", I get the error message about having node in $PATH (Node.js is at /usr/local/bin/ and is in $PATH). Console error is

Traceback (most recent call last):
  File "/Users/mahesh/Library/Application Support/Sublime Text 3/Packages/Gulp/gulp.py", line 140, in write_to_cache
    self.write_to_cache_without_js()
  File "/Users/mahesh/Library/Application Support/Sublime Text 3/Packages/Gulp/gulp.py", line 155, in write_to_cache_without_js
    raise Exception("Gulp: Could not get the current gulp version or your gulp CLI version is lower than 3.7.0")
Exception: Gulp: Could not get the current gulp version or your gulp CLI version is lower than 3.7.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mahesh/Library/Application Support/Sublime Text 3/Packages/Gulp/gulp.py", line 93, in list_tasks
    json_result = self.fetch_json()
  File "/Users/mahesh/Library/Application Support/Sublime Text 3/Packages/Gulp/gulp.py", line 125, in fetch_json
    return self.write_to_cache()
  File "/Users/mahesh/Library/Application Support/Sublime Text 3/Packages/Gulp/gulp.py", line 143, in write_to_cache
    raise Exception("\"node\" command not found.\nPlease be sure to have nodejs installed on your system and in your PATH (more info in the README).")
Exception: "node" command not found.
Please be sure to have nodejs installed on your system and in your PATH (more info in the README).

error: Gulp: "node" command not found.
Please be sure to have nodejs installed on your system and in your PATH (more info in the README).

**Comment by NicoSantangelo** [comment]
If you run `gulp` on the terminal, it works?, do you have it installed both locally and globally?

Are you on a mac? if so, before anything else try installing [SublimeFixMacPath](https://packagecontrol.io/packages/Fix%20Mac%20Path)

**Comment by NicoSantangelo** [comment]
I'm closing this for the sake of completeness, but if you were able to give my suggestion a try and the package still isn't working I'll be happy to re-open it!

**Comment by mjsarfatti** [comment]
In case somebody else stumbles here: I had the same problem, and installing SublimeFixMacPath fixed it!
