### ISSUE TITLE
gulp_kill broken since update

### ISSUE THREAD

**Issue by gethinoakes** [NicoSantangelo/sublime-gulp#73]
Hi, since the last update where you introduced being able to kill specific gulp tasks - gulp_kill no longer works for me, whether using a key binding or the menu.

**Comment by NicoSantangelo** [comment]
Hello! Thanks for the report, to be able to hunt down the problem easily, can you tell me:

- Which Sublime Text version are you running and in which OS?
- Do you see any error poping up in the Sublime Text console ? (you can open it in `View -> Show Console`

Thanks again!

**Comment by gethinoakes** [comment]
No problem:

Sublime 4114 - Windows

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\base_command.py", line 30, in run
    self.work()
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\gulp.py", line 273, in work
    ProcessCache.refresh()
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\caches.py", line 31, in refresh
    cls.each(remove_dead)
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\caches.py", line 56, in each
    fn(process)
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\caches.py", line 29, in remove_dead
    if not process.is_alive():
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\cross_platform_process.py", line 95, in is_alive
    return self._pid_exists()
  File "C:\Users\Gethin Oakes\AppData\Roaming\Sublime Text 3\Packages\Gulp\cross_platform_process.py", line 106, in _pid_exists
    found = self.pid in CrossPlatformCodecs.force_decode(stdout)
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by NicoSantangelo** [comment]
Ok! I don't have access to a Windows box right now but I'll put a patch up to fix this for everyone experiencing it.

The fix will be live on version `v6.0.1`, let me know how it goes, I'll test it as soon as I can

**Comment by gethinoakes** [comment]
Cheers, will do 👍

**Comment by NicoSantangelo** [comment]
@gethinoakes sorry to bother you again but, how did it go ?

I gave it a try in my windows box and it seemed to work fine, but I'm not entirely convinced

**Comment by gethinoakes** [comment]
@NicoSantangelo sorry I've been away over the weekend. Seems to be working fine now thanks :)

**Comment by NicoSantangelo** [comment]
🎉 Thanks for checking!
