### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by zorochimaru** [NicoSantangelo/sublime-gulp#92]
I'm doing as you wrote, 
"exec_args": {
        "path": "Z:/home/cosplay.az/www/app/"
    },
and
"gulpfile_paths": ["src", "Z:/home/cosplay.az/www/"],
but at running its not working and in command line  writes
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Users\rasim\AppData\Roaming\Sublime Text 3\Packages\Gulp\base_command.py", line 23, in run
    self.setup_data_from_settings()
  File "C:\Users\rasim\AppData\Roaming\Sublime Text 3\Packages\Gulp\base_command.py", line 33, in setup_data_from_settings
    Settings.gather_shared_data()
  File "C:\Users\rasim\AppData\Roaming\Sublime Text 3\Packages\Gulp\settings.py", line 20, in gather_shared_data
    settings = Settings()
  File "C:\Users\rasim\AppData\Roaming\Sublime Text 3\Packages\Gulp\settings.py", line 33, in __init__
    self.sources = [ProjectData(), self.user_settings]
  File "C:\Users\rasim\AppData\Roaming\Sublime Text 3\Packages\Gulp\settings.py", line 56, in __init__
    self._project_data = active_window.project_data().get(Settings.PACKAGE_NAME, {})
AttributeError: 'NoneType' object has no attribute 'get'
 what i'm doing wrong?

**Comment by NicoSantangelo** [comment]
Apologies for the delay, hope I can still help you.

I can't seem to reproduce the error. For what I can see on the stack `sublime.active_window()` is returning `None`, which shouldn't happen.
What is the result of running `sublime.active_window().project_data()` on your Sublime console? (`View -> Show Console`). I get the following

![image](https://user-images.githubusercontent.com/692077/36374636-4d24cbd4-156c-11e8-87ba-b08eaff2cf00.png)

**Comment by Zorochimaru** [comment]
Nothing :C [image: Встроенное изображение 1]

2018-02-19 15:01 GMT+04:00 Nicolás Santángelo <notifications@github.com>:

**Comment by NicoSantangelo** [comment]
Well that's weird.
Ok! I'll add a check for that case in the next release. I'll ping you as soon as it's deployed

**Comment by nicosantangelo** [comment]
Check added on v6.1.3!
