### ISSUE TITLE
Building Gulp list first time throws error

### ISSUE THREAD

**Issue by jacobraccuia** [NicoSantangelo/sublime-gulp#95]
I get this error whenever I build the gulp list for the first time after making changes.  It works afterwards.

 
> Gulp: There was an error running gulp, make sure gulp is running correctly in your project.
> For more info check the sublime-gulp.log file

I'm running sublime 3 build 3014

**Comment by NicoSantangelo** [comment]
Hey!
That's weird, do you have any info on your `sublime-gulp.log` file? on the root of your project

**Comment by NicoSantangelo** [comment]
huh, I'll try to get a windows OS setup to see if I can reproduce it. One last question, which `gulp` version are you guys running?

**Comment by jacobraccuia** [comment]
I was actually running the latest OSX. I’m using a new macbook now so I have to reinstall everything. I’ll update if I have the issue still!

**Comment by jacobraccuia** [comment]
I'm sorry this took forever to reply to.

```


05-09-2018 16:15:
fs.js:132
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:132:11)
    at Object.fs.unlink (fs.js:1002:14)
    at requireGulp (/Users/jacobraccuia/Library/Application Support/Sublime Text 3/Packages/Gulp/write_tasks_to_cache.js:30:12)
    at Object.<anonymous> (/Users/jacobraccuia/Library/Application Support/Sublime Text 3/Packages/Gulp/write_tasks_to_cache.js:83:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)

```

**Comment by NicoSantangelo** [comment]
@DiegoAz @jacobraccuia thanks a lot for your help. I finally got some free time to fix this. I'll make a new release asap

**Comment by jacobraccuia** [comment]
Thank you, seems to be working perfectly in the latest release!
