### ISSUE TITLE
ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by ghost** [NicoSantangelo/sublime-gulp#97]
I try reinstall node and gulp, but still have this issue :/

$ node -v
v10.13.0
$ npm -v
6.5.0
$ gulp -v
CLI version 2.0.1
Local version 4.0.0

NODE_PATH
C:\Users\admin\AppData\Roaming\npm

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:936:14)
    at requireGulp (C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\Gulp\write_tasks_to_cache.js:30:12)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\Gulp\write_tasks_to_cache.js:83:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by ghost** [comment]
problem was new task execution:
[read more](https://fettblog.eu/gulp-4-parallel-and-series/)

old way:
`gulp.task('autoprefixer', ['compress-css'], function() {`

new way:
`gulp.task('autoprefixer', gulp.series('compress-css'), () => {`
