### ISSUE TITLE
ERR_INVALID_CALLBACK]

### ISSUE THREAD

**Issue by sonegs** [NicoSantangelo/sublime-gulp#99]
I try to execute my gulp task but sublime text shows me this error:

fs.js:153
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:153:11)
    at Object.unlink (fs.js:1125:14)
    at requireGulp (C:\Users\sopor\AppData\Roaming\Sublime Text 3\Packages\Gulp\write_tasks_to_cache.js:30:12)
    at Object.<anonymous> (C:\Users\sopor\AppData\Roaming\Sublime Text 3\Packages\Gulp\write_tasks_to_cache.js:83:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_CALLBACK'
}

CLI version 2.3.0
Nodejs version 12.18.3
npm version 6.14.6

I tried to change the task execution method like in another issue, but it is not working.

**Comment by nicosantangelo** [comment]
It's been a while since I've used `gulp` so I'm a bit out of the loop of my own package but it looks like a CLI version problem. I'm not sure I tried running it on 2.X
I'll give it a try but does your codebase support CLI > 3?

**Comment by sonegs** [comment]
Yes it support it. The problem was solved reinstalling CLI with node_modules files in the project directory.
Thanks anyway!
